name: Greetings

on:
  issues:
    types: [opened]
  pull_request_target:
    branches: [main]

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    uses: hegerdes/helper-suite/.github/workflows/reusable-gh-greetings.yml@main
