name: Greetings

on:
  issues:
    types: [opened]
  pull_request_target:
    branches: [main]

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          issue-message: 'Hi, thank for reporting an issue, we will check it out very soon'
          pr-message: 'Hi, thank you for contributing, we will check it out very soon'
          repo-token: ${{ github.token }}
