name: Plugin Test Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["14", "16", "18"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm install

      - name: Test compile
        run: |
          # Running test
          if [[ "$(node --version)" == "v18"* ]]; then
            export NODE_OPTIONS=--openssl-legacy-provider
          fi
          npm run test-compile
